spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allowedMethods:
              - '*'
            allowedHeaders:
              - '*'
      add-to-simple-url-handler-mapping: true
      routes:
        - id: t2
          uri: http://www.taobao.com

          filters:
            - name: StripPrefix
              args:
                parts: 1
            - name: My
              args:
                isDo: true
          predicates:
            - name: Path
              args:
                pattern: /taobao/**
#      default-filters:
#        - Demo
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Method Access-Control-Allow-Headers





